services:
  postgres:
    image: postgres:16-alpine
    container_name: rent-a-car
    restart: unless-stopped
    environment:
      POSTGRES_DB: rentacar
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "8081:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
